### ISSUE TITLE
Great script, on issue

### ISSUE THREAD

**Issue by zdavatz** [jsagorin/SigningTest#1]
Hi, 

Thank you for this great script! 
One issue is left when building with the script:
```
** ARCHIVE SUCCEEDED **

Building IPA...
error: archive at path '/Users/zdavatz/Documents/xcode/generikacc/build/Generika.xcarchive' is malformed
** EXPORT FAILED **
```
any hints?

The source of the App I am trying to build is here:
https://github.com/zdavatz/generikacc

**Comment by zdavatz** [comment]
This is the solution, BTW:
https://stackoverflow.com/questions/39767214/xcarchive-malformed-due-to-missing-info-plist

**Comment by jsagorin** [comment]
thanks for reporting this. I haven't run this code since Xcode 8. I tried it again on Xcode 9. I noticed some .IPA failures too. Provision profiles mapped per bundleID too. This must be added to exportOptions plist. I'll update the blog post and source repo too.

`
<key>provisioningProfiles</key>
      <dict>
	    <key>bundleIdOfApp</key>
	    <string>DistributionProfileName or UUID of prov profile</string>
	</dict>
`

**Comment by zdavatz** [comment]
Works just fine now for Xocde 9.2! I can smoothly upload the .ipa file with 
```
+#!/bin/bash
+
+set -e
+set -u
+
+altool="$(dirname "$(xcode-select -p)")/Applications/Application Loader.app/Contents/Frameworks/ITunesSoftwareService.framework/Support/altool"
+ipa="/Users/zdavatz/Documents/xcode/generikacc/build/generika.ipa"
+
+echo "Validating app..."
+time "$altool" --validate-app --type ios --file "$ipa" --username "$ITC_USER" --password "$ITC_PASSWORD"
+echo "Uploading app to iTC..."
+time "$altool" --upload-app --type ios --file "$ipa" --username "$ITC_USER" --password "$ITC_PASSWORD"
```
